### ISSUE TITLE
Cells executable in slideshow mode

### ISSUE THREAD

**Issue by fjhickernell** [jupyterlab-contrib/rise#43]
## Description

After installing jupyterlab-rise, I can see the meta data tags for choosing which kind of slide.  However, in slideshow view the slides are not executable, even though they are in Jupyter notebook with RISE

## Reproduce

1. Create a Jupyter notebook in Jupyter Lab that contains executable Python code.
2. Using Common Tools, assign the cells to be Slides
3. Invoke slideshow mode
4. In slideshow mode edit code and execute cell

## Expected behavior

The output of the cell should change based on what has been entered, but it does not.

## Context

- Python package version:
- Python 3.9.13

Name: jupyterlab
Version: 4.0.5
Summary: JupyterLab computational environment

- Extension version:
- Name: jupyterlab_rise
Version: 0.40.0
Summary: RISE: "Live" Reveal.js JupyterLab Slideshow extension.

- Operating System and its version: MacOS Ventura 13.5.1. Apple M2 Max
- Browser and its version: 
Safari 16.6 or Jupyterlab desktop 4.0.5
<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>
qmcpy) fredhickernell@Freds-MacBook-Pro QMCSoftware % jupyter lab
[I 2023-08-20 16:49:20.259 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-08-20 16:49:20.267 ServerApp] Package jupyter_lsp took 0.0083s to import
[W 2023-08-20 16:49:20.267 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-20 16:49:20.269 ServerApp] Package jupyter_server_fileid took 0.0013s to import
[I 2023-08-20 16:49:20.274 ServerApp] Package jupyter_server_terminals took 0.0049s to import
[I 2023-08-20 16:49:20.288 ServerApp] Package jupyter_server_ydoc took 0.0135s to import
[I 2023-08-20 16:49:20.289 ServerApp] Package jupyterlab_rise took 0.0014s to import
[I 2023-08-20 16:49:20.290 ServerApp] Package nbclassic took 0.0004s to import
[W 2023-08-20 16:49:20.291 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-20 16:49:20.291 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-08-20 16:49:20.291 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-20 16:49:20.291 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-08-20 16:49:20.293 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2023-08-20 16:49:20.295 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-08-20 16:49:20.296 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[I 2023-08-20 16:49:20.299 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-08-20 16:49:20.301 ServerApp] jupyterlab_rise | extension was successfully linked.
[I 2023-08-20 16:49:20.302 ServerApp] nbclassic | extension was successfully linked.
[I 2023-08-20 16:49:20.440 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-08-20 16:49:20.490 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-08-20 16:49:20.492 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-08-20 16:49:20.492 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-08-20 16:49:20.492 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /Users/fredhickernell/SoftwareRepositories/QMCSoftware
[I 2023-08-20 16:49:20.492 FileIdExtension] ArbitraryFileIdManager : Configured database path: /Users/fredhickernell/Library/Jupyter/file_id_manager.db
[I 2023-08-20 16:49:20.493 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-08-20 16:49:20.493 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2023-08-20 16:49:20.493 FileIdExtension] Attached event listeners.
[I 2023-08-20 16:49:20.493 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-08-20 16:49:20.494 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-08-20 16:49:20.494 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2023-08-20 16:49:20.494 LabApp] JupyterLab extension loaded from /Users/fredhickernell/miniconda3/envs/qmcpy/lib/python3.9/site-packages/jupyterlab
[I 2023-08-20 16:49:20.494 LabApp] JupyterLab application directory is /Users/fredhickernell/miniconda3/envs/qmcpy/share/jupyter/lab
[I 2023-08-20 16:49:20.494 LabApp] Extension Manager is 'pypi'.
[I 2023-08-20 16:49:20.496 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-08-20 16:49:20.496 ServerApp] jupyterlab_rise | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                                                                           
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2023-08-20 16:49:20.498 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-08-20 16:49:20.499 ServerApp] Serving notebooks from local directory: /Users/fredhickernell/SoftwareRepositories/QMCSoftware
[I 2023-08-20 16:49:20.499 ServerApp] Jupyter Server 2.5.0 is running at:
[I 2023-08-20 16:49:20.499 ServerApp] http://localhost:8888/lab?token=a1eae46522caa3410e2c86172877701381af7482dd20d07f
[I 2023-08-20 16:49:20.499 ServerApp]     http://127.0.0.1:8888/lab?token=a1eae46522caa3410e2c86172877701381af7482dd20d07f
[I 2023-08-20 16:49:20.499 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-08-20 16:49:20.503 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Users/fredhickernell/Library/Jupyter/runtime/jpserver-31583-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=a1eae46522caa3410e2c86172877701381af7482dd20d07f
        http://127.0.0.1:8888/lab?token=a1eae46522caa3410e2c86172877701381af7482dd20d07f
[I 2023-08-20 16:49:20.519 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2023-08-20 16:49:23.417 LabApp] Could not determine jupyterlab build status without nodejs
[W 2023-08-20 16:49:23.819 ServerApp] Notebook demos/talk_paper_demos/Purdue_Talk_2023_March/Purdue_Talk_Figures.ipynb is not trusted
[I 2023-08-20 16:49:24.071 ServerApp] Kernel started: 5603f017-6677-4a14-a198-f4f4c047697a
[I 2023-08-20 16:49:24.483 ServerApp] Connecting to kernel 5603f017-6677-4a14-a198-f4f4c047697a.
[I 2023-08-20 16:49:24.485 ServerApp] Connecting to kernel 5603f017-6677-4a14-a198-f4f4c047697a.
[I 2023-08-20 16:49:24.485 ServerApp] Connecting to kernel 5603f017-6677-4a14-a198-f4f4c047697a.

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

**Comment by nthiery** [comment]
Just as a data point: I did not manage to reproduce; with the same jupyterlab 4.0.5 and rise 0.40.0,
I can execute cells as expected.

Ubuntu 22.04, Firefox, Python 3.11.5

**Comment by nthiery** [comment]
Ah wait, this could be related to #17: if a code cell already has content,
then that content is executed. But if there is no initial content, whatever
is typed in is ignored, and the cell is executed as an empty cell. Which
looks as if the cell had not been executed.

**Comment by trevorcampbell** [comment]
I can reproduce this.
[Screencast from 2023-09-11 03:19:02 PM.webm](https://github.com/jupyterlab-contrib/rise/assets/5981307/5b789367-02ac-435e-ad73-972a1a049a0e)

```
jupyter_client                8.3.1
jupyter_core                  5.3.1
jupyter-events                0.7.0
jupyter-lsp                   2.2.0
jupyter_server                2.7.3
jupyter-server-mathjax        0.2.6
jupyter_server_terminals      0.4.4
jupyter-telemetry             0.1.0
jupyterhub                    4.0.2
jupyterlab                    4.0.5
jupyterlab_git                0.42.0
jupyterlab-pygments           0.2.2
jupyterlab_rise               0.40.0
jupyterlab_server             2.24.0
jupyterlab-widgets            3.0.8
```

**Comment by trevorcampbell** [comment]
Ah, I should have posted my response in #48 , which I think is more what is going on in my case.

**Comment by fiware-austria** [comment]
To it looks as if the keyboard shortcut "shift-enter" does not longer execute the cell but navigates to the next slide.

**Comment by bneumayer** [comment]
I am having the same issue. The notebook seems to overrule the content in presentation mode, which does the following:
- An empty cell in the notebook cannot be executed in presentation mode. This is what causes the issue stated above by @fiware-austria: execution has no effect and the next cell is entered.
- A cell with content can be executed but changing the content in presentation mode will always produce the same output.

Maybe there is an issue with the separation of "Command Mode" and "Edit Mode"? The cells (in notebook view and presentation mode) are always marked blue but they should be green when in "Edit Mode", if I remember correctly. Also, the shortcuts seem to be "always on", e.g., when I wanted to type `# Addition` into a cell in presentation mode the speaker view opened when I typed 't'.

**Comment by AnotherCodeArtist** [comment]
I had to downgrade to version 0.2.0 to get it working again. Maybe that helps!

Would be great to get this working, since it is one of the killer-features, that sets rise apart from other presentation tools.

**Comment by bneumayer** [comment]
> I had to downgrade to version 0.2.0 to get it working again. Maybe that helps!
> 
> Would be great to get this working, since it is one of the killer-features, that sets rise apart from other presentation tools.

At our institution we used a combination of downgrading and opening the notebook in Nbclassic - not perfect but all functionalities work at the moment.

**Comment by nthiery** [comment]
Just for information: I have been using lately [JupyterLab-Deck](https://github.com/deathbeds/jupyterlab-deck). There remains a few caveats (JupyterLab 3.6 only, broken space / shift-space navigation with sublides, no conda package), but other than this it has done the job for me.

**Comment by briank-git** [comment]
If your use case allows for JupyterLab 3, I found that cells appear to work normally and run with changes with JupyterLab 3.6.6 and RISE 0.3.0.

**Comment by briank-git** [comment]
I've been looking into this issue and am hoping to get pointed in the right direction.

As a disclaimer, I'm new to JupyterLab extensions so my terminology could be very off.

Environment:
```
jupyter_client                7.4.9
jupyter_core                  5.3.1
jupyter-events                0.7.0
jupyter-lsp                   2.2.0
jupyter_server                2.10.0
jupyter_server_fileid         0.9.0
jupyter-server-mathjax        0.2.6
jupyter_server_terminals      0.4.4
jupyter_server_ydoc           0.8.0
jupyter-telemetry             0.1.0
jupyter-ydoc                  0.2.5
jupyterhub                    4.0.2
jupyterlab                    4.0.8
jupyterlab_git                0.42.0
jupyterlab-pygments           0.2.2
jupyterlab_rise               0.41.0    
jupyterlab_server             2.25.0
jupyterlab-widgets            3.0.9
```
Here is what I found so far:

For example if I create a notebook with a single empty cell, open it in RISE, change the cell's contents to `print("test")`, and then save with `Cmd+s`, the JupyterLab API PUT request shows the cell source as empty (shown below). Running the cell outputs nothing and the cell edit is not shown in the original notebook.

```
Contents of PUT request to http://127.0.0.1:8888/api/contents/examples/issue-43.ipynb?1699395590087:

{"name": "issue-43.ipynb", "path": "examples/issue-43.ipynb", "last_modified": "2023-11-07T22:19:50.127128Z", "created": "2023-11-07T22:19:50.127128Z", "content": {"cells": [{"cell_type": "code", "execution_count": null, "id": "86e79d67-836a-4d98-8ac5-441c84ef1a3d", "metadata": {"trusted": true}, "outputs": [], "source": ""}], "metadata": {"kernelspec": {"display_name": "Python 3 (ipykernel)", "language": "python", "name": "python3"}, "language_info": {"codemirror_mode": {"name": "ipython", "version": 3}, "file_extension": ".py", "mimetype": "text/x-python", "name": "python", "nbconvert_exporter": "python", "pygments_lexer": "ipython3", "version": "3.11.5"}}, "nbformat": 4, "nbformat_minor": 5}, "format": "json", "mimetype": null, "size": 617, "writable": true, "type": "notebook"}
```

Which seems to indicate the notebook the slides are generated from is not listening to changes in cell content or the cells themselves do not recognize when their content changes, which may be the case as the `jp-mod-dirty` CSS class is also not added by a cell when edited. 

However if I add a new cell, delete, or split a cell, and then save, the original notebook will show that change.

I tried commenting out all of the code that turns a NotebookPanel into a Reveal slideshow in `packages/application/src/plugins/rise.ts` so that RISE essentially just opens a regular notebook (i.e. just docmanager.open and then app.shell.add), but the same issue occurs so likely none of the Reveal related code is the cause.

I thought maybe the RISE server extension, but it seems there weren't any major differences between the 0.3.x branch (which appears to not have this issue with JupyterLab 3.6.6) and the main branch in terms of the server extension.

I did notice this error in the console which may or may not be relevant:
```
index.js:225 Error: Shared module codemirror doesn't exist in shared scope default
    at l (remoteEntry.265228b546125022c5c6.js:1:6646)
    at remoteEntry.265228b546125022c5c6.js:1:7688
    at remoteEntry.265228b546125022c5c6.js:1:7596
    at 8681 (remoteEntry.265228b546125022c5c6.js:1:10005)
    at remoteEntry.265228b546125022c5c6.js:1:10786
    at Array.forEach (<anonymous>)
    at x.f.consumes (remoteEntry.265228b546125022c5c6.js:1:10616)
    at remoteEntry.265228b546125022c5c6.js:1:1174
    at Array.reduce (<anonymous>)
    at x.e (remoteEntry.265228b546125022c5c6.js:1:1152)
```

Thanks!

**Comment by trevorcampbell** [comment]
FWIW: after PR #62 was merged, I can now reliably edit and execute code in RISE slides.
