### ISSUE TITLE
Fragments are not shown when navigating through slides 

### ISSUE THREAD

**Issue by briank-git** [jupyterlab-contrib/rise#66]
## Description

When a slide with fragments is reached, pressing the right arrow key on the keyboard will not reveal any fragments. If the right or down arrow is pressed enough times, the slideshow will just advance to the next slide.

If the left arrow is pressed to go to a previous slide with fragments, it will sometimes show a button that says "+ n cells hidden" which when clicked will allow fragments to be shown as they should (sequentially as the right or down arrow is pressed).

![fragment_issue](https://github.com/jupyterlab-contrib/rise/assets/59274601/d97197c8-b26a-4f29-a395-cf86e3868c4c)

Edit: Upon further inspection, could this be caused by a conflict with JupyterLab's key bindings below?
<img width="543" alt="image" src="https://github.com/jupyterlab-contrib/rise/assets/59274601/30e5a983-c60b-4efe-b594-262c84cd8676">

Update: It appears that right and left arrow keys work for showing fragments when I disable the above bindings that collapse and expand headings.

## Reproduce

1. Go to a slide that contains fragments
2. Press the right arrow key to reveal the fragments
3. Fragments will not be shown and if right or down keys are pressed enough times, the slideshow will just advance to the next slide

## Expected behavior

On a slide with fragments, fragments should be revealed one by one as right arrow key is pressed and disappear one by one as left arrow key is pressed.

## Context

```
jupyter_client                8.4.0
jupyter_core                  5.4.0
jupyter-events                0.8.0
jupyter-lsp                   2.2.0
jupyter-resource-usage        1.0.1
jupyter_server                2.8.0
jupyter-server-mathjax        0.2.6
jupyter_server_terminals      0.4.4
jupyter-telemetry             0.1.0
jupyterhub                    4.0.2
jupyterlab                    4.0.7
jupyterlab_git                0.50.0
jupyterlab-pygments           0.2.2
jupyterlab_rise               0.42.0
jupyterlab_server             2.25.0
jupyterlab-widgets            3.0.9
```

- Python package version:
```
jupyterlab_rise               0.42.0
```
- Extension version:
```
JupyterLab v4.0.7
/opt/conda/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        jupyterlab-rise v0.42.0 enabled OK (python, jupyterlab_rise)
        nbgrader v0.9.1 enabled OK (python, nbgrader)
        nbdime-jupyterlab v3.0.1 enabled OK
        @jupyter-notebook/lab-extension v7.0.6 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.9 enabled OK (python, jupyterlab_widgets)
        @jupyterlab/git v0.50.0 enabled OK (python, jupyterlab-git)
        @jupyter-server/resource-usage v1.0.1 enabled OK (python, jupyter-resource-usage)
```
- Operating System and its version: Ubuntu 22.04
- Browser and its version: Chrome Version 120.0.6099.109

<details><summary>Command Line Output</summary>
<pre>
[I 2024-01-09 23:35:18.467 ServerApp] Package jupyterlab took 0.0000s to import
[I 2024-01-09 23:35:18.496 ServerApp] Package jupyter_lsp took 0.0275s to import
[W 2024-01-09 23:35:18.497 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-01-09 23:35:18.531 ServerApp] Package jupyter_resource_usage took 0.0335s to import
[I 2024-01-09 23:35:18.535 ServerApp] Package jupyter_server_mathjax took 0.0030s to import
[I 2024-01-09 23:35:18.547 ServerApp] Package jupyter_server_terminals took 0.0110s to import
[I 2024-01-09 23:35:18.601 ServerApp] Package jupyterlab_git took 0.0526s to import
[I 2024-01-09 23:35:18.607 ServerApp] Package nbclassic took 0.0046s to import
[W 2024-01-09 23:35:18.611 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-01-09 23:35:18.613 ServerApp] Package nbdime took 0.0000s to import
[I 2024-01-09 23:35:18.616 ServerApp] Package nbgitpuller took 0.0022s to import
[I 2024-01-09 23:35:18.616 ServerApp] Package notebook took 0.0000s to import
[I 2024-01-09 23:35:18.622 ServerApp] Package notebook_shim took 0.0000s to import
[W 2024-01-09 23:35:18.622 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-01-09 23:35:18.623 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-01-09 23:35:18.623 ServerApp] jupyter_resource_usage | extension was successfully linked.
[I 2024-01-09 23:35:18.635 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2024-01-09 23:35:18.646 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-01-09 23:35:18.660 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-01-09 23:35:18.660 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2024-01-09 23:35:18.673 ServerApp] nbclassic | extension was successfully linked.
[I 2024-01-09 23:35:18.673 ServerApp] nbdime | extension was successfully linked.
[I 2024-01-09 23:35:18.673 ServerApp] nbgitpuller | extension was successfully linked.
[I 2024-01-09 23:35:18.686 ServerApp] notebook | extension was successfully linked.
[I 2024-01-09 23:35:19.182 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-01-09 23:35:19.275 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-01-09 23:35:19.283 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-01-09 23:35:19.285 ServerApp] jupyter_resource_usage | extension was successfully loaded.
[I 2024-01-09 23:35:19.286 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2024-01-09 23:35:19.288 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-01-09 23:35:19.294 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.11/site-packages/jupyterlab
[I 2024-01-09 23:35:19.294 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2024-01-09 23:35:19.295 LabApp] Extension Manager is 'pypi'.
[I 2024-01-09 23:35:19.303 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-01-09 23:35:19.318 ServerApp] jupyterlab_git | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                                                                           
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2024-01-09 23:35:19.327 ServerApp] nbclassic | extension was successfully loaded.
[I 2024-01-09 23:35:19.489 ServerApp] nbdime | extension was successfully loaded.
[I 2024-01-09 23:35:19.491 ServerApp] nbgitpuller | extension was successfully loaded.
[I 2024-01-09 23:35:19.501 ServerApp] notebook | extension was successfully loaded.
[I 2024-01-09 23:35:19.503 ServerApp] Serving notebooks from local directory: /home/jovyan/work
[I 2024-01-09 23:35:19.503 ServerApp] Jupyter Server 2.8.0 is running at:
[I 2024-01-09 23:35:19.503 ServerApp] http://f14e809267be:8888/lab?token=dca36728917e3878105d5796c7922b1d0b481b908c63ec47
[I 2024-01-09 23:35:19.504 ServerApp]     http://127.0.0.1:8888/lab?token=dca36728917e3878105d5796c7922b1d0b481b908c63ec47
[I 2024-01-09 23:35:19.504 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-01-09 23:35:19.514 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-317-open.html
    Or copy and paste one of these URLs:
        http://f14e809267be:8888/lab?token=dca36728917e3878105d5796c7922b1d0b481b908c63ec47
        http://127.0.0.1:8888/lab?token=dca36728917e3878105d5796c7922b1d0b481b908c63ec47
[I 2024-01-09 23:35:22.566 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server

</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
7 from @jupyterlab/application-top of shared singleton module @jupyterlab/translation (required ^4.0.9)
c @ remoteEntry.64949938345da5069400.js:1
remoteEntry.64949938345da5069400.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/ui-components (required ^4.0.9)
c @ remoteEntry.64949938345da5069400.js:1
remoteEntry.64949938345da5069400.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/notebook (required ^4.0.9)
c @ remoteEntry.64949938345da5069400.js:1
remoteEntry.64949938345da5069400.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/settingregistry (required ^4.0.9)
c @ remoteEntry.64949938345da5069400.js:1
remoteEntry.64949938345da5069400.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/application (required ^4.0.9)
c @ remoteEntry.64949938345da5069400.js:1
remoteEntry.64949938345da5069400.js:1 Unsatisfied version 4.1.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/apputils (required ^4.1.9)
c @ remoteEntry.64949938345da5069400.js:1
remoteEntry.64949938345da5069400.js:1 No satisfying version (^4.0.9) of shared module @jupyterlab/docregistry found in shared scope default.
Available versions: 4.0.7 from @jupyterlab/application-top
c @ remoteEntry.64949938345da5069400.js:1
remoteEntry.64949938345da5069400.js:1 Unsatisfied version 6.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/coreutils (required ^6.0.9)
c @ remoteEntry.64949938345da5069400.js:1
remoteEntry.370de6f77fd53f20b297.js:1 Unsatisfied version 7.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/services (required ^7.0.9)
p @ remoteEntry.370de6f77fd53f20b297.js:1
remoteEntry.370de6f77fd53f20b297.js:1 Unsatisfied version 4.1.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/apputils (required ^4.1.9)
p @ remoteEntry.370de6f77fd53f20b297.js:1
remoteEntry.370de6f77fd53f20b297.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/codemirror (required ^4.0.9)
p @ remoteEntry.370de6f77fd53f20b297.js:1
remoteEntry.370de6f77fd53f20b297.js:1 Unsatisfied version 6.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/coreutils (required ^6.0.9)
p @ remoteEntry.370de6f77fd53f20b297.js:1
remoteEntry.370de6f77fd53f20b297.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/codeeditor (required ^4.0.9)
p @ remoteEntry.370de6f77fd53f20b297.js:1
remoteEntry.370de6f77fd53f20b297.js:1 No satisfying version (^4.0.9) of shared module @jupyterlab/nbformat found in shared scope default.
Available versions: 4.0.7 from @jupyterlab/application-top
p @ remoteEntry.370de6f77fd53f20b297.js:1
remoteEntry.370de6f77fd53f20b297.js:1 Unsatisfied version 1.0.2 from @jupyterlab/application-top of shared singleton module @jupyter/ydoc (required ^1.1.1)
p @ remoteEntry.370de6f77fd53f20b297.js:1
remoteEntry.370de6f77fd53f20b297.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/settingregistry (required ^4.0.9)
p @ remoteEntry.370de6f77fd53f20b297.js:1
remoteEntry.370de6f77fd53f20b297.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/translation (required ^4.0.9)
p @ remoteEntry.370de6f77fd53f20b297.js:1
remoteEntry.370de6f77fd53f20b297.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/notebook (required ^4.0.9)
p @ remoteEntry.370de6f77fd53f20b297.js:1
remoteEntry.370de6f77fd53f20b297.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/rendermime (required ^4.0.9)
p @ remoteEntry.370de6f77fd53f20b297.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 7.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/services (required ^7.0.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/statusbar (required ^4.0.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/docmanager (required ^4.0.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/filebrowser (required ^4.0.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/application (required ^4.0.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/ui-components (required ^4.0.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 No satisfying version (^4.0.9) of shared module @jupyterlab/outputarea found in shared scope default.
Available versions: 4.0.7 from @jupyterlab/application-top
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/mainmenu (required ^4.0.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 4.1.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/apputils (required ^4.1.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/codemirror (required ^4.0.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 No satisfying version (^4.0.9) of shared module @jupyterlab/docregistry found in shared scope default.
Available versions: 4.0.7 from @jupyterlab/application-top
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 6.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/coreutils (required ^6.0.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/codeeditor (required ^4.0.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 No satisfying version (^4.0.9) of shared module @jupyterlab/nbformat found in shared scope default.
Available versions: 4.0.7 from @jupyterlab/application-top
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 1.0.2 from @jupyterlab/application-top of shared singleton module @jupyter/ydoc (required ^1.1.1)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/settingregistry (required ^4.0.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/translation (required ^4.0.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
remoteEntry.9b08bf4afadafb4454e8.js:1 Unsatisfied version 4.0.7 from @jupyterlab/application-top of shared singleton module @jupyterlab/rendermime (required ^4.0.9)
p @ remoteEntry.9b08bf4afadafb4454e8.js:1
manager.js:49 Language pack 'en_US' not installed!
fetch @ manager.js:49
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
898.9e08659f55f7a47080b1.js?v=9e08659f55f7a47080b1:1 JupyterLab extension jupyterlab-rise is activated!
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
index.es6.js:9745 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
attachWidget @ index.es6.js:9745
Show 1 more frame
Show less
settingregistry.js:862 Skipping this shortcut because it collides with another shortcut. Object
(anonymous) @ settingregistry.js:862
Show 1 more frame
Show less
settingregistry.js:889 Skipping this default shortcut because it collides with another default shortcut. Object
(anonymous) @ settingregistry.js:889
Show 1 more frame
Show less
toc.js:492 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at Pe (toc.js:492:17)
    at toc.js:400:41
    at Array.forEach (<anonymous>)
    at s (toc.js:398:41)
    at c (toc.js:459:17)
    at m (index.es6.js:555:18)
    at Object.l [as emit] (index.es6.js:513:17)
    at a.emit (index.es6.js:112:17)
    at we._onCellInViewportChanged (widget.js:652:37)
    at m (index.es6.js:555:18)
/jupyter/user/brian/rise/dsci-100-instructor/R/slides/01_intro_jupyter_r.ipynb?activeCellIndex=0:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1 Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm was closed too early
_loadFromKernel @ 336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1
remoteEntry.64949938345da5069400.js:1 Unsatisfied version 4.0.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/translation (required ^4.0.9)
c @ remoteEntry.64949938345da5069400.js:1
remoteEntry.64949938345da5069400.js:1 Unsatisfied version 4.0.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/ui-components (required ^4.0.9)
c @ remoteEntry.64949938345da5069400.js:1
remoteEntry.64949938345da5069400.js:1 Unsatisfied version 4.0.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/notebook (required ^4.0.9)
c @ remoteEntry.64949938345da5069400.js:1
remoteEntry.64949938345da5069400.js:1 Unsatisfied version 4.0.3 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/settingregistry (required ^4.0.9)
c @ remoteEntry.64949938345da5069400.js:1

</pre>
</details>

**Comment by briank-git** [comment]
Appears to be fixed in JupyterLab v4.1.2 onwards. Selectors for ArrowRight and ArrowLeft are now more specific ".jp-Notebook.jp-mod-commandMode:not(.jp-mod-readWrite) :focus" instead of just ".jp-Notebook:focus.jp-mod-commandMode" and are no longer triggered within RISE.

Recommendation is to update to the latest version of JupyterLab.
